version: 2
builds:
  - main: "./cmd/aicommit"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.Version={{.Version}}"
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "arm"
    binary: "{{ .ProjectName }}"
nfpms:
  - vendor: Coder Technologies Inc.
    homepage: https://coder.com/
    maintainer: Ammar Bandukwala <ammar@coder.com>
    description: |-
      aicommit is a small command line tool for generating commit messages
    license: CC0-1.0
    contents:
      - src: LICENSE
        dst: "/usr/share/doc/{{ .ProjectName }}/copyright"
    formats:
      - apk
      - deb
archives:
  - id: "zip"
    format: zip
  - id: "tarball"
    format: tar.gz
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

# release:
#   draft: true
changelog:
  use: github-native
